.TH BABI 5 2024-10-15 "Cab8a9e" "Cabbage Eater's Diary"
.SH NAME
babi \- Bikkie's Abstract Brush Information file
.SH DESCRIPTION
The babi family of filetypes is used for storing uncompiled .bsp brush & entity data
.SH VARIANTS
.SS BABI
Bikkie's Abstract Brush Information \- UTF-8 Encoded
.SS BABIZ
BABI with appended ZIP containing assets
